"""Initial tables: users, words, word_progress

Revision ID: a93f64b8188d
Revises: 
Create Date: 2026-01-08 15:13:42.451285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a93f64b8188d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('words',
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('translation', sa.String(length=200), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=True),
    sa.Column('sentence_zh', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_word'), 'words', ['word'], unique=True)
    op.create_table('word_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('pool', sa.String(length=10), nullable=False),
    sa.Column('learned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_practice_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_available_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_in_review_phase', sa.Boolean(), nullable=False),
    sa.Column('review_completed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_word')
    )
    op.create_index(op.f('ix_word_progress_next_available_time'), 'word_progress', ['next_available_time'], unique=False)
    op.create_index(op.f('ix_word_progress_pool'), 'word_progress', ['pool'], unique=False)
    op.create_index(op.f('ix_word_progress_user_id'), 'word_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_word_progress_word_id'), 'word_progress', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_progress_word_id'), table_name='word_progress')
    op.drop_index(op.f('ix_word_progress_user_id'), table_name='word_progress')
    op.drop_index(op.f('ix_word_progress_pool'), table_name='word_progress')
    op.drop_index(op.f('ix_word_progress_next_available_time'), table_name='word_progress')
    op.drop_table('word_progress')
    op.drop_index(op.f('ix_words_word'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
